# Pre-commit configuration
# Run `pre-commit install` to set up the git hook scripts

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(md|txt|yaml|yml)$
      - id: end-of-file-fixer
        files: \.(md|txt|yaml|yml)$
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"] # Limit files to 500KB
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"] # Enforce Unix line endings
      - id: fix-byte-order-marker
      - id: check-symlinks
      - id: check-executables-have-shebangs
        exclude: \.(md|txt)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: ["--fix", "--config", ".markdownlint.json"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(md|yaml|yml)$
        args: ["--write", "--prose-wrap=always"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
      - id: ruff-format

default_language_version:
  python: python3

exclude: |
  (?x)^(
    \.git/|
    \.vscode/|
    \.idea/|
    node_modules/|
    .*\.docx$|
    .*\.pptx$|
    .*\.lock$|
    templates/.*YYYYMMDD.*
  )$
